/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi;
import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author LENOVO
 */
public class TDP extends javax.swing.JFrame {

    /**
     * Creates new form TDP
     */
    public TDP() {
        initComponents();
        table_show();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kembali_btn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pegawai = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_tlp = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kembali_btn.setBackground(new java.awt.Color(255, 255, 255));
        kembali_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aset/kembaliBut.png"))); // NOI18N
        kembali_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembali_btnActionPerformed(evt);
            }
        });
        jPanel1.add(kembali_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 100, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aset/tambahBut.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 100, 30));

        deletebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aset/hapusBut.png"))); // NOI18N
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });
        jPanel1.add(deletebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 100, 30));

        editbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aset/editBut.png"))); // NOI18N
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });
        jPanel1.add(editbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 100, 30));

        pegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Pegawai", "Nama Pegawai", "Alamat", "Nomor telp"
            }
        ));
        pegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pegawaiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(pegawai);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 610, 220));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aset/TDPtxt.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aset/IDtxt.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aset/NamaPegawaitxt.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aset/Alamattxt.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aset/NomorTelptxt.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, -1));
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 170, 30));

        txt_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 170, 30));

        txt_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_alamatActionPerformed(evt);
            }
        });
        jPanel1.add(txt_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 170, 30));

        txt_tlp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tlpActionPerformed(evt);
            }
        });
        jPanel1.add(txt_tlp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 170, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps;
        ResultSet rs;
        
        String sql = "DELETE FROM pegawai WHERE id_pegawai=?";
        
        DefaultTableModel model = (DefaultTableModel) pegawai.getModel();
        int selectedIndex = pegawai.getSelectedRow();
        
        try{
            int id = Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());
            int dialogResult = JOptionPane.showConfirmDialog(null, "apakah yakin?","warning",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){
                ps = koneksi.getConnection().prepareStatement(sql);
                ps.setInt(1, id);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "data berhasil di hapus!");
                
                txt_id.setText("");
                txt_nama.setText("");
                txt_alamat.setText("");
                txt_tlp.setText("");
                txt_id.requestFocus();
                table_show();
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps;
        int id = Integer.parseInt(txt_id.getText());
        String nama = txt_nama.getText();
        String alamat = txt_alamat.getText();
        int tlp = Integer.parseInt(txt_tlp.getText());
        String query = "INSERT INTO pegawai(id_pegawai,nama_pegawai,alamat,no_hp)VALUES(?,?,?,?)";
        try{
            ps = koneksi.getConnection().prepareStatement(query);
            ps.setInt(1, id);
            ps.setString(2, nama);
            ps.setString(3, alamat);
            ps.setInt(4, tlp);
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Data Di Simpan!");
            
            txt_id.setText("");
            txt_nama.setText("");
            txt_alamat.setText("");
            txt_tlp.setText("");
            txt_id.requestFocus();
            table_show();
            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaActionPerformed

    private void txt_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_alamatActionPerformed

    private void txt_tlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tlpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tlpActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        // TODO add your handling code here:
        PreparedStatement ps;
        ResultSet rs;
        String sql = "UPDATE pegawai set nama_pegawai=?, alamat=?, no_hp=? WHERE id_pegawai=?";
        DefaultTableModel model = (DefaultTableModel) pegawai.getModel();
        int SelectedIndex = pegawai.getSelectedRow();
        try{
            int id = Integer.parseInt(model.getValueAt(SelectedIndex, 0).toString());
            String nama = txt_nama.getText();
            String alamat = txt_alamat.getText();
            int tlp = Integer.parseInt(txt_tlp.getText());
            
            ps = koneksi.getConnection().prepareStatement(sql);
            ps.setString(1, nama);
            ps.setString(2, alamat);
            ps.setInt(3, tlp);
            ps.setInt(4, id);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data berhasil Di Ubah");
            
            txt_id.setText("");
            txt_nama.setText("");
            txt_alamat.setText("");
            txt_tlp.setText("");
            txt_id.requestFocus();
            table_show();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_editbtnActionPerformed

    private void pegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pegawaiMouseClicked
        // TODO add your handling code here:
         DefaultTableModel model = (DefaultTableModel) pegawai.getModel();
        
        int SelectedRowIndex = pegawai.getSelectedRow();
        
        txt_nama.setText(model.getValueAt(SelectedRowIndex, 1).toString());
        txt_alamat.setText(model.getValueAt(SelectedRowIndex, 2).toString());
        txt_tlp.setText(model.getValueAt(SelectedRowIndex, 3).toString());
    }//GEN-LAST:event_pegawaiMouseClicked

    private void kembali_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembali_btnActionPerformed
        // TODO add your handling code here:
        mainmenuadmin ma = new mainmenuadmin();
        ma.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_kembali_btnActionPerformed

    private void table_show(){
        int cc;
        PreparedStatement ps;
        ResultSet rs;
        String sql = "SELECT *FROM pegawai";
        try{
            ps = koneksi.getConnection().prepareStatement(sql);
            rs = ps.executeQuery();
            ResultSetMetaData RSMD = rs.getMetaData();
            cc = RSMD.getColumnCount();
            DefaultTableModel DFT = (DefaultTableModel) pegawai.getModel();
            DFT.setRowCount(0);
            
            while(rs.next()){
                Vector v2 = new Vector();
                for(int i =1; i<=cc; i++){
                    v2.add(rs.getInt("id_pegawai"));
                    v2.add(rs.getString("nama_pegawai"));
                    v2.add(rs.getString("alamat"));
                    v2.add(rs.getInt("no_hp"));
                }
                DFT.addRow(v2);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TDP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TDP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TDP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TDP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TDP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton editbtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembali_btn;
    private javax.swing.JTable pegawai;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_tlp;
    // End of variables declaration//GEN-END:variables
}
